const MyAnalyzeButtonActionsConstants = {
  UPLOAD_ACTION: 'UPLOAD_ACTION',
  UPLOAD_FILES_ACTION: 'UPLOAD_FILES_ACTION',
  DONE_ACTION: 'DONE_ACTION',
  DONE_FILES_ACTION: 'DONE_FILES_ACTION',
  FAILURE_ACTION: 'FAILURE_ACTION',
  FAILURE_FILES_ACTION: 'FAILURE_FILES_ACTION'
};

export { MyAnalyzeButtonActionsConstants };
